Repository 1024pix/notify-team-on-config-file-change, pull requests merged in 2023-05, with the labels that each got.

#8 [BUGFIX] L'envoi de message échoue car le nom du channel est utilisé à la place de l'identifiant (PIX-7898)
  .circleci/config.yml
  .env.sample
  .gitignore
  .nvmrc
  action.yml
  index.js
  lib/server.js
  package-lock.json
  package.json
  tests/ingegration/github.test.js
  tests/ingegration/list-pr-commit.js
Labels: Tech Review OK, team-captains

#9 Release v1.0.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, cross-team

#10 [BUGFIX] Les tests comportent des erreur d'orthographe
  tests/integration/github.test.js
  tests/integration/list-pr-commit.js
Labels: Tech Review OK, cross-team

#11 [TECH] Releaser vraiment la v1.0.4
  dist/index.js
  dist/licenses.txt
Labels: Tech Review OK, cross-team
